TEXTS = {
    'uz': {
        'welcome': "🤖 Assalomu alaykum! SmartMobile.Botiga\n🛍️ Xush kelibsiz!",
        'choose_lang': "🌐 Tilni tanlang:",
        'ask_name': "✍️ Ismingizni yozing:",
        'ask_phone': "📱 Telefon raqamingizni yuboring:",
        'ask_location': "📍 Joylashuvingizni yuboring:",
        'checking': "⏳ Ma'lumotlaringiz tekshirilmoqda{}",
        'registered': "✅ Ro'yxatdan o'tish tasdiqlandi!",
        'main_menu': "🔽 Quyidagi bo'limlardan birini tanlang:",
        'back': "🔙 Orqaga",
        'no_ads': "📭 Bu brendda hozircha elonlar mavjud emas",
        'choose_brand': "📱 Brendni tanlang:",
        'favorites': "❤️ Sevimlilar",
        'no_favorites': "📭 Sevimlilar bo'limi bo'sh",
        'exchange_title': "🔄 Ayirboshlash bo'limi",
        'choose_wanted_brand': "📱 Qaysi brenddagi telefon kerak?",
        'choose_wanted_model': "📱 Qaysi model kerak?",
        'choose_offer_brand': "📱 Siz qaysi brenddagi telefonni taklif qilasiz?",
        'choose_offer_model': "📱 Qaysi modelni taklif qilasiz?",
        'ask_exchange_desc': "📝 Telefoningiz haqida qisqacha ma'lumot yozing:",
        'exchange_sent': "✅ Taklifingiz adminga yuborildi! Tez orada ko'rib chiqiladi.",
        'support': "📞 Qo'llab-quvvatlash: +998880445550",
        'seller_contact': "👤 Sotuvchi bilan aloqa: +998880445550",
        'error': "❌ Xatolik yuz berdi. Qayta urinib ko'ring.",
        'not_registered': "❌ Iltimos avval /start buyrug'i orqali ro'yxatdan o'ting!"
    },
    'ru': {
        'welcome': "🤖 Ассаламу алейкум! Добро пожаловать в SmartMobile.Bot\n🛍️ Добро пожаловать!",
        'choose_lang': "🌐 Выберите язык:",
        'ask_name': "✍️ Напишите ваше имя:",
        'ask_phone': "📱 Отправьте ваш номер телефона:",
        'ask_location': "📍 Отправьте ваше местоположение:",
        'checking': "⏳ Проверка ваших данных{}",
        'registered': "✅ Регистрация подтверждена!",
        'main_menu': "🔽 Выберите один из разделов:",
        'back': "🔙 Назад",
        'no_ads': "📭 В этом бренде пока нет объявлений",
        'choose_brand': "📱 Выберите бренд:",
        'favorites': "❤️ Избранное",
        'no_favorites': "📭 Раздел избранного пуст",
        'exchange_title': "🔄 Раздел обмена",
        'choose_wanted_brand': "📱 Телефон какого бренда вам нужен?",
        'choose_wanted_model': "📱 Какая модель нужна?",
        'choose_offer_brand': "📱 Телефон какого бренда вы предлагаете?",
        'choose_offer_model': "📱 Какую модель предлагаете?",
        'ask_exchange_desc': "📝 Напишите краткую информацию о вашем телефоне:",
        'exchange_sent': "✅ Ваше предложение отправлено администратору! Скоро будет рассмотрено.",
        'support': "📞 Поддержка: +998880445550",
        'seller_contact': "👤 Связаться с продавцом: +998880445550",
        'error': "❌ Произошла ошибка. Попробуйте снова.",
        'not_registered': "❌ Пожалуйста, сначала зарегистрируйтесь через команду /start!"
    }
}